# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-19 02:53
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'app', '0001_squashed_0016_auto_20160711_1619'), (b'app', '0002_auto_20160714_1451'), (b'app', '0003_auto_20160714_1505'), (b'app', '0004_auto_20160714_1506'), (b'app', '0005_auto_20160714_1509'), (b'app', '0006_auto_20160714_1536'), (b'app', '0007_auto_20160714_1538'), (b'app', '0008_auto_20160719_1119'), (b'app', '0009_auto_20160719_1122'), (b'app', '0010_auto_20160809_1832'), (b'app', '0011_remove_biomsearchjob_otu_text'), (b'app', '0012_auto_20160810_1320'), (b'app', '0013_auto_20160814_1645'), (b'app', '0014_auto_20160815_1213')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecosystem', models.CharField(max_length=60, verbose_name='Ecosystem Type')),
                ('ecosystem_proper_name', models.CharField(default='Test', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BiomSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ManyToManyField(max_length=3, to=b'app.EcosystemChoice')),
                ('biom_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_path_handler)),
                ('status', models.IntegerField(choices=[(-1, b'Stopped'), (1, b'Queued'), (0, b'Validating'), (2, b'Processing'), (10, b'Completed')], default=0)),
                ('error_code', models.IntegerField(choices=[(0, b'No errors.'), (1, b'File/text content has errors. Check JSON/TSV content.'), (2, b'Too many samples, only 1 sample allowed.'), (3, b'Duplicate observation IDs.'), (-1, b'Error opening uploaded file. Contact site admin.'), (4, b'Some OTUs do not exist in the database. Cannot proceed.'), (5, b'An error occurred. This may be a problem with the system. Try again or contact site admin.')], default=0)),
                ('sample_name', models.CharField(default=b'(no name)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ecosystemchoice',
            name='ecosystem_proper_name',
            field=models.CharField(max_length=60),
        ),
    ]
