# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 12:31
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'app', '0001_initial'), (b'app', '0002_auto_20160217_1515'), (b'app', '0003_auto_20160218_1039'), (b'app', '0004_job_completed'), (b'app', '0005_auto_20160224_1127'), (b'app', '0006_job_result'), (b'app', '0007_auto_20160315_1755'), (b'app', '0008_xuser'), (b'app', '0009_auto_20160315_1829'), (b'app', '0010_auto_20160319_1212'), (b'app', '0011_auto_20160523_0038'), (b'app', '0012_auto_20160523_0055'), (b'app', '0013_auto_20160630_1522'), (b'app', '0014_auto_20160630_1526'), (b'app', '0015_auto_20160711_1148'), (b'app', '0016_auto_20160711_1619')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('otu_text', models.TextField(default=None)),
                ('criteria', models.ManyToManyField(max_length=3, to=b'app.EcosystemChoice')),
                ('biom_file', models.FileField(blank=True, null=True, upload_to=app.models.upload_path_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecosystem', models.CharField(max_length=60, verbose_name='Ecosystem Type')),
                ('ecosystem_proper_name', models.CharField(default='Test', max_length=60)),
            ],
        ),
    ]
