# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0016_auto_20160711_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomsearchjob',
            name='completed',
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='status',
            field=models.IntegerField(choices=[(-1, b'Stopped'), (0, b'Queued'), (1, b'Processing'), (2, b'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='ecosystemchoice',
            name='ecosystem_proper_name',
            field=models.CharField(max_length=60),
        ),
    ]
