# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160714_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomSearchJobError',
            fields=[
                ('error_code', models.IntegerField(primary_key=True, serialize=False)),
                ('error_message', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='error_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.BiomSearchJobError'),
            preserve_default=False,
        ),
    ]
