# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160908_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='normalized_otu',
            field=models.BooleanField(default=False),
        ),
    ]
