# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160714_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomsearchjob',
            name='error_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.BiomSearchJobError'),
        ),
    ]
