# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_biomsearchjob_normalized_otu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomsearchjob',
            old_name='normalized_otu',
            new_name='is_normalized_otu',
        ),
    ]
