# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 13:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170208_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomsearchjob',
            name='sample_name',
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='name',
            field=models.CharField(default=b'Unnamed Job', max_length=100, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z\\s]*$', b'Only alphanumeric characters and spaces allowed')]),
        ),
        migrations.AlterField(
            model_name='biomsearchjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
