# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_job_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
