# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160714_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomsearchjoberror',
            old_name='error_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='biomsearchjoberror',
            old_name='error_message',
            new_name='message',
        ),
    ]
