# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170213_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='app.BiomSearchJob')),
            ],
        ),
    ]
