# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 13:55
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_job_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomSearchJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('criteria', models.CharField(default='all', max_length=200)),
                ('input_file', models.FileField(default=None, upload_to=app.models.upload_path_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='result',
            field=models.TextField(),
        ),
    ]
