# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160714_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomsearchjob',
            name='error_code',
            field=models.IntegerField(choices=[(0, b'No errors.'), (1, b'File/text content has errors. Only JSON or TSV content allowed.'), (2, b'Too many samples, only 1 sample allowed.'), (3, b'Duplicate observation IDs.')], default=0),
        ),
        migrations.AlterField(
            model_name='biomsearchjob',
            name='status',
            field=models.IntegerField(choices=[(-1, b'Stopped'), (1, b'Queued'), (0, b'Validating'), (2, b'Processing'), (3, b'Completed')], default=1),
        ),
    ]
