# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170220_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='last_run_at',
            field=models.DateTimeField(null=True),
        ),
    ]
