# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160719_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomsearchjob',
            name='status',
            field=models.IntegerField(choices=[(-1, b'Stopped'), (1, b'Queued'), (0, b'Validating'), (2, b'Processing'), (3, b'Completed')], default=0),
        ),
    ]
