# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_biomsearchjob_last_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='alpha_rarefaction_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='range_query_value',
            field=models.FloatField(choices=[(0.1, b'0.1'), (0.2, b'0.2'), (0.3, b'0.3'), (0.4, b'0.4'), (0.5, b'0.5')], default=0.3),
        ),
        migrations.AlterField(
            model_name='biomsearchjob',
            name='analysis_type',
            field=models.IntegerField(choices=[(1, b'Bray Curtis'), (2, b'GNAT/UniFrac')], default=2),
        ),
    ]
