# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160809_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomsearchjob',
            name='otu_text',
        ),
    ]
