# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160319_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecosystem', models.CharField(help_text='Select the ecosystem(s)', max_length=200, verbose_name='Ecosystem Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='biomsearchjob',
            name='criteria',
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='criteria',
            field=models.ManyToManyField(to='app.EcosystemChoices'),
        ),
    ]
