# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-16 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170316_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomsearchjob',
            old_name='alpha_rarefaction_flag',
            new_name='adaptive_rarefaction_flag',
        ),
    ]
