# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160523_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecosystemchoices',
            name='ecosystem_proper_name',
            field=models.CharField(default='Test', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecosystemchoices',
            name='ecosystem',
            field=models.CharField(max_length=60, verbose_name='Ecosystem Type'),
        ),
    ]
