# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170316_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
