# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 11:22
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160523_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='biom_file',
            field=models.FileField(default=None, null=True, upload_to=app.models.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='biomsearchjob',
            name='criteria',
            field=models.ManyToManyField(max_length=3, to='app.EcosystemChoices'),
        ),
    ]
