# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_biomsearchjob_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyLevelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_level', models.CharField(max_length=60, verbose_name=b'Taxonomy Chart Level')),
                ('taxon_level_proper_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='biomsearchjob',
            name='taxon_levels',
            field=models.ManyToManyField(max_length=3, to='app.TaxonomyLevelChoice'),
        ),
    ]
