# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160810_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomsearchjob',
            name='sample_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biomsearchjob',
            name='error_code',
            field=models.IntegerField(choices=[(0, b'No errors.'), (1, b'File/text content has errors. Check JSON/TSV content.'), (2, b'Too many samples, only 1 sample allowed.'), (3, b'Duplicate observation IDs.'), (-1, b'Error opening uploaded file. Contact site admin.'), (4, b'Some OTUs do not exist in the database. Cannot proceed.'), (5, b'An error occurred. This may be a problem with the system. Try again or contact site admin.')], default=0),
        ),
    ]
