# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-10 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170610_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomsearchjob',
            old_name='taxon_levels',
            new_name='taxonomy_levels',
        ),
    ]
