# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160630_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcosystemChoices',
            new_name='EcosystemChoice',
        ),
    ]
