# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-11 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20160711_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
